import {
  IconAccessible,
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowNarrowRight,
  IconBaselineDensityMedium,
  IconBaselineDensitySmall,
  IconBattery,
  IconBell,
  IconBook,
  IconCalendar,
  IconCalendarEvent,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconCheck,
  IconChevronDown,
  IconChevronRight,
  IconCircleCheck,
  IconCloudUpload,
  IconCoins,
  IconCommand,
  IconComponents,
  IconDeviceDesktop,
  IconDeviceMobile,
  IconDots,
  IconDotsVertical,
  IconDownload,
  IconDroplet,
  IconFile,
  IconFileText,
  IconFilter,
  IconFlag,
  IconFolder,
  IconHelpCircle,
  IconHistory,
  IconHourglass,
  IconInbox,
  IconInfoCircle,
  IconKeyboard,
  IconLayoutDashboard,
  IconLayoutGrid,
  IconLayoutRows,
  IconLayoutSidebar,
  IconLink,
  IconMenu2,
  IconMessage,
  IconMoon,
  IconPencil,
  IconPercentage,
  IconPhoto,
  IconPlus,
  IconRefresh,
  IconRobot,
  IconRoute,
  IconScale,
  IconSearch,
  IconSelector,
  IconSend,
  IconSparkles,
  IconSquareSmall,
  IconStar,
  IconTable,
  IconTag,
  IconTextDirectionRtl,
  IconThermometer,
  IconToggle,
  IconTrendingUp,
  IconUser,
  IconUsers,
  IconWand,
  IconWorld,
  type Icon,
} from '@syntara/icons';

/**
 * Sidebar icons, keyed by href: the hand-written guide pages, then every component. Components were text-only
 * until 2026-10-08, when Anuj asked for an icon beside each name. Lives client-side because icon components
 * can't cross the server → client prop boundary that NavGroup travels on.
 */
export const DOC_ICONS: Readonly<Record<string, Icon>> = {
  '/docs': IconBook,
  '/docs/installation': IconDownload,
  '/docs/mcp': IconRobot,
  '/docs/server-driven-ui': IconDeviceMobile,
  '/docs/figma': IconPencil,
  '/docs/theming': IconAdjustmentsHorizontal,
  '/docs/color': IconDroplet,
  '/docs/dark-mode': IconMoon,
  '/docs/rtl': IconTextDirectionRtl,
  '/docs/density': IconBaselineDensityMedium,
  '/docs/accessibility': IconAccessible,
  '/docs/icons': IconSparkles,
  '/docs/governance': IconScale,
  '/docs/raise-a-conflict': IconMessage,
  '/docs/changelog': IconHistory,

  '/docs/components': IconComponents,
  '/docs/components/accordion': IconPlus,
  '/docs/components/alert': IconAlertCircle,
  '/docs/components/alert-dialog': IconAlertTriangle,
  '/docs/components/amount': IconCoins,
  '/docs/components/area-chart': IconChartLine,
  '/docs/components/avatar': IconUser,
  '/docs/components/badge': IconStar,
  '/docs/components/bar-chart': IconChartBar,
  '/docs/components/breadcrumbs': IconChevronRight,
  '/docs/components/button': IconSquareSmall,
  '/docs/components/calendar': IconCalendar,
  '/docs/components/card': IconLayoutDashboard,
  '/docs/components/chart': IconChartPie,
  '/docs/components/checkbox': IconCheck,
  '/docs/components/chip': IconFilter,
  '/docs/components/combobox': IconSelector,
  '/docs/components/command': IconCommand,
  '/docs/components/data-table': IconTable,
  '/docs/components/date-picker': IconCalendarEvent,
  '/docs/components/dialog': IconDeviceDesktop,
  '/docs/components/empty-state': IconInbox,
  '/docs/components/eyebrow': IconFlag,
  '/docs/components/file-upload': IconCloudUpload,
  '/docs/components/footer': IconLayoutRows,
  '/docs/components/hero': IconPhoto,
  '/docs/components/icon-tile': IconComponents,
  '/docs/components/kbd': IconKeyboard,
  '/docs/components/link': IconLink,
  '/docs/components/marquee': IconArrowNarrowRight,
  '/docs/components/menu': IconDotsVertical,
  '/docs/components/meter': IconThermometer,
  '/docs/components/navbar': IconMenu2,
  '/docs/components/pagination': IconDots,
  '/docs/components/person-chip': IconUsers,
  '/docs/components/popover': IconInfoCircle,
  '/docs/components/progress': IconBattery,
  '/docs/components/prompt-composer': IconSend,
  '/docs/components/radio-group': IconCircleCheck,
  '/docs/components/search-field': IconSearch,
  '/docs/components/select': IconChevronDown,
  '/docs/components/separator': IconBaselineDensitySmall,
  '/docs/components/sheet': IconFile,
  '/docs/components/sidebar': IconLayoutSidebar,
  '/docs/components/skeleton': IconHourglass,
  '/docs/components/slider': IconAdjustmentsHorizontal,
  '/docs/components/sparkline': IconTrendingUp,
  '/docs/components/spinner': IconRefresh,
  '/docs/components/stat-tile': IconPercentage,
  '/docs/components/steps': IconRoute,
  '/docs/components/streaming-response': IconWand,
  '/docs/components/switch': IconToggle,
  '/docs/components/tabs': IconFolder,
  '/docs/components/tag': IconTag,
  '/docs/components/text-area': IconFileText,
  '/docs/components/text-field': IconPencil,
  '/docs/components/theme-scope': IconWorld,
  '/docs/components/toast': IconBell,
  '/docs/components/toggle-group': IconLayoutGrid,
  '/docs/components/tooltip': IconHelpCircle,
};
